# Generated by Django 2.2.1 on 2021-02-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Poll', verbose_name='опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=256, verbose_name='шапка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('OA', 'один ответ'), ('MA', 'несколько ответов'), ('WA', 'письменный ответ')], default=1, max_length=2, verbose_name='тип вопроса'),
        ),
    ]
