# Generated by Django 2.2.1 on 2021-02-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210215_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Poll', verbose_name='опрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice', verbose_name='вариант ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('OA', 'один ответ'), ('MA', 'несколько ответов'), ('WA', 'письменный ответ')], default='OA', max_length=2, verbose_name='тип вопроса'),
        ),
    ]
